spring:
  application:
    name: AI-Agent
  config:
    import: classpath:config.properties
  datasource:
    url: jdbc:h2:mem:testdb
    username: my_user
    password: Suxinwei123
    driver-class-name: org.postgresql.Driver
  ai:
    dashscope:
      api-key: ${API_KEY}
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:1.5b
# \u4E34\u65F6\u6CE8\u91CA\u6389\uFF0C\u4FBF\u4E8E\u5927\u5BB6\u5F00\u53D1\u8C03\u8BD5\u548C\u90E8\u7F72\uFF08\u5B9E\u9645\u9700\u8981\u542F\u52A8 MCP \u670D\u52A1\uFF09
    mcp:
      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
        stdio:
          servers-configuration: classpath:mcp-servers.json
# \u4E34\u65F6\u6CE8\u91CA\u6389\uFF0C\u4FBF\u4E8E\u5927\u5BB6\u5F00\u53D1\u8C03\u8BD5\u548C\u90E8\u7F72\uFF08\u5B9E\u9645\u586B\u5199 PgVector \u6570\u636E\u5E93\u4FE1\u606F\uFF09
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1536
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.sigma.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# \u4FEE\u6539\u65E5\u5FD7\u7EA7\u522B\uFF0C\u67E5\u770B Spring AI \u66F4\u591A\u8C03\u7528\u7EC6\u8282
logging:
  level:
    org.springframework.ai: DEBUG
# searchAPI
search-api:
  # \u9700\u8981\u66FF\u6362\u4E3A\u4F60\u81EA\u5DF1\u7684 key
  api-key: ${search-api-key}